In [2]:
# Ignoring irrelevant warnings 

import warnings
warnings.filterwarnings("ignore")

In [30]:
# Importing required libraries 

import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from imblearn.pipeline import make_pipeline as imb_make_pipeline
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.ensemble import BalancedBaggingClassifier, EasyEnsemble
from mlens.visualization import corrmat
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.ensemble.partial_dependence import plot_partial_dependence
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (roc_auc_score, confusion_matrix,
                             accuracy_score, roc_curve,
                             precision_recall_curve, f1_score)
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score
import xgboost as xgb
from keras import models, layers, optimizers

In [5]:
# Importing the train dataset 

train = pd.read_csv("/home/amresh/Desktop/datasets/loan_prediction_ml_hiring_challenge/train.csv")

In [6]:
# Configuring the notebook to show all features 

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [8]:
# Top 10 rows of the train dataset 

train.head(10)

        loan_id source       financial_institution  interest_rate  unpaid_principal_bal  loan_term origination_date first_payment_date  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score loan_purpose  insurance_percent  co-borrower_credit_score  insurance_type  m1  m2  m3  m4  m5  m6  m7  m8  m9  m10  m11  m12  m13
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250                214000        360       2012-03-01            05/2012             95                  1.0                  22.0                  694.0          C86               30.0                       0.0             0.0   0   0   0   0   0   0   1   0   0    0    0    0    1
1  672831657627      Y  Swanson, Newton and Miller          4.875                144000        360       2012-01-01            03/2012             72                  1.0                  44.0                  697.0          B12                0.0                       0.0             0.0   0   0   0   0   0   0   0   0   0    0    1    0    1
2  742515242108      Z              Thornton-Davis          3.250                366000        180       2012-01-01            03/2012             49                  1.0                  33.0                  780.0          B12                0.0                       0.0             0.0   0   0   0   0   0   0   0   0   0    0    0    0    1
3  601385667462      X                       OTHER          4.750                135000        360       2012-02-01            04/2012             46                  2.0                  44.0                  633.0          B12                0.0                     638.0             0.0   0   0   0   0   0   0   0   0   1    1    1    1    1
4  273870029961      X                       OTHER          4.750                124000        360       2012-02-01            04/2012             80                  1.0                  43.0                  681.0          C86                0.0                       0.0             0.0   0   1   2   3   4   5   6   7   8    9   10   11    1
5  769060024464      Y               Browning-Hart          4.375                150000        360       2012-02-01            04/2012             80                  1.0                  46.0                  675.0          C86                0.0                       0.0             0.0   1   0   0   0   0   0   0   0   0    0    0    0    1
6  148071614687      X                       OTHER          4.000                 59000        360       2012-02-01            04/2012             95                  1.0                  44.0                  723.0          C86               30.0                       0.0             0.0   0   0   0   0   0   0   0   0   0    0    0    0    1
7  853383953266      Y               Browning-Hart          4.500                319000        300       2012-01-01            03/2012             62                  1.0                  45.0                  652.0          A23                0.0                       0.0             0.0   0   1   0   0   0   0   0   0   0    0    0    0    1
8  423590072335      X               Browning-Hart          4.000                520000        360       2012-03-01            05/2012             76                  1.0                  35.0                  808.0          C86                0.0                       0.0             0.0   0   0   0   0   1   0   1   0   1    2    0    1    1
9  308990846816      X                       OTHER          4.000                214000        360       2012-01-01            03/2012             95                  2.0                  41.0                  702.0          A23               30.0                     700.0             0.0   0   0   0   0   0   1   1   1   1    1    2    2    1

In [9]:
train.size

3365682

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116058 entries, 0 to 116057
Data columns (total 29 columns):
loan_id                     116058 non-null int64
source                      116058 non-null object
financial_institution       116058 non-null object
interest_rate               116058 non-null float64
unpaid_principal_bal        116058 non-null int64
loan_term                   116058 non-null int64
origination_date            116058 non-null object
first_payment_date          116058 non-null object
loan_to_value               116058 non-null int64
number_of_borrowers         116058 non-null float64
debt_to_income_ratio        116058 non-null float64
borrower_credit_score       116058 non-null float64
loan_purpose                116058 non-null object
insurance_percent           116058 non-null float64
co-borrower_credit_score    116058 non-null float64
insurance_type              116058 non-null float64
m1                          116058 non-null int64
m2                          116058 non-null int64
m3                          116058 non-null int64
m4                          116058 non-null int64
m5                          116058 non-null int64
m6                          116058 non-null int64
m7                          116058 non-null int64
m8                          116058 non-null int64
m9                          116058 non-null int64
m10                         116058 non-null int64
m11                         116058 non-null int64
m12                         116058 non-null int64
m13                         116058 non-null int64
dtypes: float64(7), int64(17), object(5)
memory usage: 25.7+ MB

In [12]:
train.isna().sum()

loan_id                     0
source                      0
financial_institution       0
interest_rate               0
unpaid_principal_bal        0
loan_term                   0
origination_date            0
first_payment_date          0
loan_to_value               0
number_of_borrowers         0
debt_to_income_ratio        0
borrower_credit_score       0
loan_purpose                0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
m1                          0
m2                          0
m3                          0
m4                          0
m5                          0
m6                          0
m7                          0
m8                          0
m9                          0
m10                         0
m11                         0
m12                         0
m13                         0
dtype: int64

In [15]:
# Selecting the training features 

X_train = train.drop(columns=['loan_id', 'm13'])

In [16]:
# Selecting the output feature

y_train = train['m13']

In [17]:
# Checking the balance of output feature 

number_of_non_delequent = train['m13'].value_counts()[0]
number_of_delequent = train['m13'].value_counts()[1]

In [18]:
percent_delequent = (number_of_delequent / train['m13'].count()) * 100
percent_delequent

0.5480018611383963

In [19]:
percent_non_delequent = (number_of_non_delequent / train['m13'].count()) * 100
percent_non_delequent

99.45199813886161

<h3><i><b>It can be seen that the output variable is very imbalanced.</b></i></h3>

In [21]:
# creating dummy variables for object type columns 

X_train = pd.get_dummies(X_train, drop_first=True)

In [23]:
X_train.head()

,interest_rate,unpaid_principal_bal,loan_term,loan_to_value,number_of_borrowers,debt_to_income_ratio,borrower_credit_score,insurance_percent,co-borrower_credit_score,insurance_type,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,source_Y,source_Z,financial_institution_Browning-Hart,financial_institution_Chapman-Mcmahon,"financial_institution_Cole, Brooks and Vincent",financial_institution_Edwards-Hoffman,"financial_institution_Martinez, Duffy and Bird","financial_institution_Miller, Mcclure and Allen",financial_institution_Nicholson Group,financial_institution_OTHER,financial_institution_Richards-Walters,financial_institution_Richardson Ltd,"financial_institution_Romero, Woods and Johnson","financial_institution_Sanchez, Hays and Wilkerson",financial_institution_Sanchez-Robinson,financial_institution_Suarez Inc,"financial_institution_Swanson, Newton and Miller","financial_institution_Taylor, Hunt and Rodriguez",financial_institution_Thornton-Davis,"financial_institution_Turner, Baldwin and Rhodes",origination_date_2012-02-01,origination_date_2012-03-01,first_payment_date_03/2012,first_payment_date_04/2012,first_payment_date_05/2012,loan_purpose_B12,loan_purpose_C86
0,4.250,214000,360,95,1.0,22.0,694.0,30.0,0.0,0.0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,1
1,4.875,144000,360,72,1.0,44.0,697.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
2,3.250,366000,180,49,1.0,33.0,780.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0
3,4.750,135000,360,46,2.0,44.0,633.0,0.0,638.0,0.0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0
4,4.750,124000,360,80,1.0,43.0,681.0,0.0,0.0,0.0,0,1,2,3,4,5,6,7,8,9,10,11,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1

In [24]:
# models 

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import BernoulliNB
from sklearn.neighbors import KNeighborsClassifier

nb_clf = BernoulliNB(alpha=1.2, binarize=0.0)
svc_clf = SVC(kernel='linear')
xgb_clf = XGBClassifier()
gb_clf = GradientBoostingClassifier(learning_rate=0.2, loss='exponential', n_estimators=25)
bag_clf = BaggingClassifier()
ada_clf = AdaBoostClassifier()
rf_clf = RandomForestClassifier()
lr_clf = LogisticRegression()
knn_clf = KNeighborsClassifier()

In [25]:
# Selecting the best features using Recursive Feature Elimination 

from sklearn.feature_selection import RFE

selector = RFE(rf_clf)
selector = selector.fit(X_train, y_train)
selector.ranking_
temp = pd.Series(selector.support_,index = X_train.columns)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

Index(['interest_rate', 'unpaid_principal_bal', 'loan_term', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'insurance_percent', 'co-borrower_credit_score', 'm4', 'm5', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12', 'source_Y', 'financial_institution_Browning-Hart', 'financial_institution_OTHER', 'origination_date_2012-02-01', 'first_payment_date_03/2012', 'loan_purpose_B12', 'loan_purpose_C86'], dtype='object')

In [26]:
# Dropping the least important features 

X_train = X_train.drop(columns=['number_of_borrowers', 'insurance_type', 'm1', 'm2', 'm3', 'source_Z', 'financial_institution_Chapman-Mcmahon', 'financial_institution_Cole, Brooks and Vincent', 'financial_institution_Edwards-Hoffman', 'financial_institution_Martinez, Duffy and Bird', 'financial_institution_Miller, Mcclure and Allen', 
                      'financial_institution_Nicholson Group', 'financial_institution_Richards-Walters', 
                      'financial_institution_Richardson Ltd', 'financial_institution_Romero, Woods and Johnson', 
                      'financial_institution_Sanchez, Hays and Wilkerson', 'financial_institution_Sanchez-Robinson', 
                      'financial_institution_Suarez Inc', 'financial_institution_Swanson, Newton and Miller',
       'financial_institution_Taylor, Hunt and Rodriguez', 'financial_institution_Thornton-Davis', 
                      'financial_institution_Turner, Baldwin and Rhodes'
                     ])

In [ ]:
# Trying different techniques to handle imbalanced dataset 

# Build model with no sampling
pip_orig = make_pipeline(gb_clf)

scores = cross_val_score(pip_orig,
                         X_train, y_train,
                         scoring="f1", cv=10)
print(f"Original model's average f1 score: {scores.mean():.5f}")


# Build model with undersampling
pip_undersample = imb_make_pipeline(
                                    RandomUnderSampler(), gb_clf)
scores = cross_val_score(pip_undersample,
                         X_train, y_train,
                         scoring="f1", cv=10)
print(f"Under-sampled model's average f1 score: {scores.mean():.5f}")


# Build model with oversampling
pip_oversample = imb_make_pipeline(
                                    RandomOverSampler(), gb_clf)
scores = cross_val_score(pip_oversample,
                         X_train, y_train,
                         scoring="f1", cv=10)
print(f"Over-sampled model's average f1 score: {scores.mean():.5f}")

# Build model with EasyEnsemble
resampled_rf = BalancedBaggingClassifier(base_estimator=gb_clf,
                                         n_estimators=10, random_state=123)
pip_resampled = make_pipeline(resampled_rf)


# predictions = pip_resampled.fit(X_train, y_train)                             
scores = cross_val_score(pip_resampled,
                         X_train, y_train,
                         scoring="f1", cv=10)
print(f"EasyEnsemble model's average f1 score: {scores.mean():.5f}")


# Build model with SMOTE
pip_smote = imb_make_pipeline(
                              SMOTE(), gb_clf)
predictions = pip_smote.fit(X_train, y_train)
scores = cross_val_score(pip_smote,
                         X_train, y_train,
                         scoring="f1", cv=10)
print(f"SMOTE model's average f1 score: {scores.mean():.5f}")

Original model's average f1 score: 0.50305
Under-sampled model's average f1 score: 0.06506
Over-sampled model's average f1 score: 0.07010
EasyEnsemble model's average f1 score: 0.07081

In [26]:
# grid search for the best model 

from sklearn.model_selection import GridSearchCV

parameters = {
    'n_estimators': [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    'criterion': ['gini', 'entropy'],
    'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 
    'bootstrap': [True, False]
    }

clf = GridSearchCV(rf_clf, parameters, cv=3, n_jobs=-1)

clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.best_params_)

KeyboardInterrupt:

In [73]:
# doing prediction on the test data provided 

X_test = pd.read_csv('/home/amresh/Desktop/datasets/loan_prediction_ml_hiring_challenge/test.csv')
loan_id = X_test.loan_id
X_test = X_test.drop(columns=['loan_id'])

object_columns_test = list(X_test.select_dtypes(include=['object']).columns)
X_test = pd.get_dummies(X_test, columns=object_columns_test, drop_first=True)
X_test = X_test.drop(columns=['number_of_borrowers', 'insurance_type', 'm1', 'm2', 'm3', 'source_Z', 'financial_institution_Chapman-Mcmahon', 'financial_institution_Cole, Brooks and Vincent', 'financial_institution_Edwards-Hoffman', 'financial_institution_Martinez, Duffy and Bird', 'financial_institution_Miller, Mcclure and Allen', 
                      'financial_institution_Nicholson Group', 'financial_institution_Richards-Walters', 
                      'financial_institution_Richardson Ltd', 'financial_institution_Romero, Woods and Johnson', 
                      'financial_institution_Sanchez, Hays and Wilkerson', 'financial_institution_Sanchez-Robinson', 
                      'financial_institution_Suarez Inc', 'financial_institution_Swanson, Newton and Miller',
       'financial_institution_Taylor, Hunt and Rodriguez', 'financial_institution_Thornton-Davis', 
                      'financial_institution_Turner, Baldwin and Rhodes'])
predicted = pip_smote.predict(X_test)

In [74]:
# Generating the submission file 

submission = pd.DataFrame({'loan_id': loan_id, 'm13': predicted })
submission.to_csv("submission_gbc_smote_grid_search.csv", index=False)